# Mapping Defaults
default_mapping = "passthrough" 
layout_swap_key = "0x10" # "Globe" key

# Comma-separated list of available layouts. Must match filenames in mapping_directory
# This is the order they will be cycled through.
available = "passthrough,f_keys,WoW,other_game"
mapping_directory = "keymaps/"

#Neopixel Defaults
brightness = 3 # TOML only supports integers so scale in code.
color = "blue" 
num_pixels = 1 

# Performance Settings
debug_mode = "false"
